[package]
name = "orx-concurrent-bag"
version = "3.0.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient, convenient and lightweight grow-only concurrent data structure allowing high performance concurrent collection."
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-concurrent-bag/"
keywords = ["concurrency", "bag", "data-structures", "atomic", "lock-free"]
categories = ["data-structures", "concurrency", "rust-patterns", "no-std"]

[dependencies]
orx-pseudo-default = { version = "2.0.0", default-features = false }
orx-pinned-vec = { path = "../orx-pinned-vec" }
orx-fixed-vec = { path = "../orx-fixed-vec" }
orx-split-vec = { path = "../orx-split-vec" }
orx-pinned-concurrent-col = { path = "../orx-pinned-concurrent-col" }

[dev-dependencies]
criterion = "0.5.1"
rand = "0.9.0"
rayon = "1.10.0"
test-case = "3.3.1"
append-only-vec = "0.1.7"
boxcar = "0.2.8"
orx-iterable = "1.1.1"

[[bench]]
name = "collect_with_extend"
harness = false
