[package]
name = "orx-concurrent-bag"
version = "1.3.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient, convenient and lightweight grow-only concurrent collection, ideal for collecting results concurrently."
license = "MIT"
repository = "https://github.com/orxfun/orx-concurrent-bag/"
keywords = ["concurrency", "bag", "data-structures", "collect"]
categories = ["data-structures", "concurrency", "rust-patterns"]

[dependencies]
orx-fixed-vec = "2.4"
orx-pinned-vec = "2.4"
orx-split-vec = "2.5"


[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
rayon = "1.9.0"
test-case = "3.3.1"

[[bench]]
name = "grow"
harness = false
