[package]
name = "orx-concurrent-bag"
version = "1.0.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "A thread-safe collection allowing growth with immutable reference, making it ideal for collecting results concurrently."
license = "MIT"
repository = "https://github.com/orxfun/orx-concurrent-bag/"
keywords = ["vec", "array", "split", "fragments", "pinned"]
categories = ["data-structures", "rust-patterns"]

[dependencies]
orx-split-vec = "2.3"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
test-case = "3.3.1"

[[bench]]
name = "grow"
harness = false
