name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable"]

    steps:
    - uses: actions/checkout@v5

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}

    - name: Install clippy
      run: rustup component add clippy
    - name: Install 32bit target
      run: rustup target add i686-unknown-linux-musl
    - name: Install wasm target
      run: rustup target add wasm32v1-none
      
    - name: Build
      run: cargo build --verbose
    - name: Build-32bit
      run: cargo build --verbose --target i686-unknown-linux-musl
    - name: Build-wasm
      run: cargo build --verbose --target wasm32v1-none

    - name: Test
      run: cargo test --verbose
    - name: Test-32bit
      run: cargo test --verbose --target i686-unknown-linux-musl
    - name: Check-wasm
      run: cargo check --verbose --target wasm32v1-none

    - name: Clippy
      run: cargo clippy -- -D warnings --verbose
  
    - name: NoStd
      run: cargo +nightly no-std-check

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install Rust nightly with miri
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri

    - name: Run miri tests
      env:
        CARGO_INCREMENTAL: 0
      run: cargo +nightly miri test --lib --bins --tests --verbose
